version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend_v2/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - backend_v2/.env
    volumes:
      - ./backend_v2/app:/app
    restart: always

  frontend:
    build:
      context: .
      dockerfile: rag-frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./rag-frontend:/app
    restart: always
